# -*- coding: utf-8 -*-
"""Mammographic.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1svv1AhHaqSIVxBguD2lOkGSvrGmku3w2
"""

!pip install pycaret

import pandas as pd
import numpy as np

from google.colab import drive
drive.mount("/content/gdrive")

# Import dataset
dataset = pd.read_csv('/content/gdrive/My Drive/Colab Notebooks/mammographic_dataset_final.csv')

#Converting dummies
dataset = pd.get_dummies(dataset)
dataset.head(10)

from pycaret.utils import enable_colab
enable_colab()

# Splitting data for testing
data = dataset.sample(frac=0.9, random_state=786)
data_unseen = dataset.drop(data.index)

data.reset_index(drop=True, inplace=True)
data_unseen.reset_index(drop=True, inplace=True)

print('Data for Modeling: ' + str(data.shape))
print('Unseen Data For Predictions: ' + str(data_unseen.shape))

from pycaret.classification import *
exp_reg101 = setup(data = data, target = 'Severity', session_id=123)

# Pyrcaret will run through 25 models and choose the average of the best 10 modes 
best_model = compare_models()

# Our best model is Logistic Regression with accurary = 0.8257
print(best_model)

# Mean accuracy is the same with the above result
lr = create_model('lr')

# After Hyper-parameter optimization
tuned_lr = tune_model(lr)

# Validate our model
plot_model(tuned_lr, 'auc')

plot_model(tuned_lr, plot='feature')

plot_model(tuned_lr, plot = 'confusion_matrix')

predict_model(tuned_lr);

final_lr = finalize_model(tuned_lr)

predict_model(final_lr);

unseen_predictions = predict_model(final_lr, data=data_unseen)
unseen_predictions.head()