# -*- coding: utf-8 -*-
"""Mammographic.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1svv1AhHaqSIVxBguD2lOkGSvrGmku3w2
"""

!pip install pycaret

from pycaret.utils import enable_colab
enable_colab()

from google.colab import drive
drive.mount("/content/gdrive")

import pandas as pd
dataset = pd.read_csv('/content/gdrive/My Drive/Colab Notebooks/mammographic_dataset_final.csv')

print(dataset.columns)

data = dataset.sample(frac=0.9, random_state=786)
data_unseen = dataset.drop(data.index)

data.reset_index(drop=True, inplace=True)
data_unseen.reset_index(drop=True, inplace=True)

print('Data for Modeling: ' + str(data.shape))
print('Unseen Data For Predictions: ' + str(data_unseen.shape))

from pycaret.classification import *
exp_reg101 = setup(data = data, target = 'Severity', session_id=123)

best_model = compare_models()

print(best_model)

rf = create_model('rf')

tuned_rf = tune_model(rf)

plot_model(tuned_rf, 'auc')

plot_model(tuned_rf, plot='feature')

plot_model(tuned_rf, plot = 'confusion_matrix')

predict_model(tuned_rf);

final_rf = finalize_model(tuned_rf)

predict_model(final_rf);

unseen_predictions = predict_model(final_rf, data=data_unseen)
unseen_predictions.head()